In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
path="/content/gdrive/My Drive/ Dataset/fraud_details_cleaned.csv"

Mounted at /content/gdrive

In [2]:
mat=pd.read_csv(path)
df=pd.DataFrame(mat)

In [3]:
df.head()

,SERVICE_NO,FRAUD_NUMBER,Date,FRAUD_TYPE,OBSERVATIONS,REFERENCE_DIRECTION,TOTAL_RECOVERED_AMOUNT,RECORD_NUMBER,STATUS,APPLIANCE_CODE,POWER,QUANTITY,HOURS_OF_USE_PER_DAY
0,201995931,496808.0,2020-02-13,DIRECT CONNECTION ON SUPPLY WIRE,PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...,EKOUNOU,112105.0,435204984.0,PAID UNDER INSTALMENT AGREEMENT,COMPUTER,200.0,1.0,8.0
1,200872755,224397.0,2011-12-15,SHUNT ON CURRENT WINDING IN THE METER,SHUNT BOBINE INTENSITE,OYOM ABANG,475486.0,241419588.0,PAID UNDER INSTALMENT AGREEMENT,TELEVISEUR/VACUUM CLEANER/FAX,100.0,3.0,10.0
2,200264239,200867.0,2011-04-25,SHUNT ON CURRENT WINDING IN THE METER,,TUNEL LOGBABA,511261.0,221271745.0,PAID UNDER INSTALMENT AGREEMENT,REFRIGERATOR 250L,190.0,1.0,14.0
3,200062554,389751.0,2016-06-09,GAP OF ATTACK WHEEL COMPARE TO THE UNLIMITED S...,DEUX BOBINES FLUX DECONNECTEES DANS LE COMPTEUR,QT BONAPRISO,641597.0,332281283.0,PAID,FREEZER 375L,160.0,2.0,14.0
4,200318029,398508.0,2016-11-23,DIRECT CONNECTION ON BURRIED CABLE,MINUTERIE 5/15 JAUNE DANS LE CPT 10/60A AVEC S...,QT BONABERI,1841235.0,343215232.0,POTENTIAL WRITE-OFF,ELECTRIC IRON,1000.0,1.0,2.0

In [4]:
# Rename columns to meaningful names
df.columns = [
                    # Unnamed: 0
    'customer_number',         # NIS_RAD
    'fraud_case_number',       # NUM_FR
    'detection_date',          # F_DETEC
    'fraud_type',              # TIPO(TR.TIP_FRA)
    'fraud_observation',       # OBS_FRA
    'address_reference',       # REF_DIR
    'total_recovered_amount',  # IMP_TOT_REC
    'recovery_number',         # NUM_REC
    'account_status',          # ESTADO(RE.EST_ACT)
    'device_code',             # CODIGO(AP.CO_APARATO)
    'power_capacity_kw',       # POTENCIA
    'quantity',                # CANTIDAD
    'daily_usage_hours'        # HORAS_USO_DIA
]


print(df.head())

   customer_number  fraud_case_number detection_date  \
0        201995931           496808.0     2020-02-13
1        200872755           224397.0     2011-12-15
2        200264239           200867.0     2011-04-25
3        200062554           389751.0     2016-06-09
4        200318029           398508.0     2016-11-23

                                          fraud_type  \
0                   DIRECT CONNECTION ON SUPPLY WIRE
1             SHUNT ON CURRENT WINDING IN THE METER
2             SHUNT ON CURRENT WINDING IN THE METER
3  GAP OF ATTACK WHEEL COMPARE TO THE UNLIMITED S...
4                 DIRECT CONNECTION ON BURRIED CABLE

                                   fraud_observation address_reference  \
0  PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...           EKOUNOU
1                             SHUNT BOBINE INTENSITE        OYOM ABANG
2                                                        TUNEL LOGBABA
3    DEUX BOBINES FLUX DECONNECTEES DANS LE COMPTEUR      QT BONAPRISO
4  MINUTERIE 5/15 JAUNE DANS LE CPT 10/60A AVEC S...       QT BONABERI

   total_recovered_amount  recovery_number                   account_status  \
0                112105.0      435204984.0  PAID UNDER INSTALMENT AGREEMENT
1                475486.0      241419588.0  PAID UNDER INSTALMENT AGREEMENT
2                511261.0      221271745.0  PAID UNDER INSTALMENT AGREEMENT
3                641597.0      332281283.0                             PAID
4               1841235.0      343215232.0              POTENTIAL WRITE-OFF

                     device_code  power_capacity_kw  quantity  \
0                       COMPUTER              200.0       1.0
1  TELEVISEUR/VACUUM CLEANER/FAX              100.0       3.0
2              REFRIGERATOR 250L              190.0       1.0
3                   FREEZER 375L              160.0       2.0
4                  ELECTRIC IRON             1000.0       1.0

   daily_usage_hours
0                8.0
1               10.0
2               14.0
3               14.0
4                2.0

In [5]:
df.loc[0]

customer_number                                                   201995931
fraud_case_number                                                  496808.0
detection_date                                                   2020-02-13
fraud_type                                 DIRECT CONNECTION ON SUPPLY WIRE
fraud_observation         PIQUAGE SUR LE RESEAU D'ALIMENTATION A L'AIDE ...
address_reference                                                   EKOUNOU
total_recovered_amount                                             112105.0
recovery_number                                                 435204984.0
account_status                              PAID UNDER INSTALMENT AGREEMENT
device_code                                                        COMPUTER
power_capacity_kw                                                     200.0
quantity                                                                1.0
daily_usage_hours                                                       8.0
Name: 0, dtype: object

In [6]:
df.account_status.value_counts()

account_status
POTENTIAL WRITE-OFF                             37860
PAID UNDER INSTALMENT AGREEMENT                 36289
PAID                                            32978
CANCELLED                                       11210
SUSPENDED                                        6633
SENT TO CUSTOMER                                 1692
UNDER INSTALMENT AGREEMENT                        920
BILLED                                            467
MANUAL DEFINITE WRITE-OFF                         395
FINAL DEMAND LETTER                               105
CANCELLED DUE TO TRANSFER TO ANOTHER ACCOUNT       71
SUSPENSION PROCESS DETAINED                        56
AUTOMATICALLY COLLECTED STAFF INVOICE              20
AUTOMATICALLY COLLECTED ZERO AMOUNT                 4
MANUAL POTENTIAL WRITE-OFF                          2
Name: count, dtype: int64

In [7]:
fraud_statuses = [
    'POTENTIAL WRITE-OFF',
    'MANUAL DEFINITE WRITE-OFF',
    'MANUAL POTENTIAL WRITE-OFF',
    'SUSPENDED',
    'SUSPENSION PROCESS DETAINED',
    'FINAL DEMAND LETTER',
    'CANCELLED',
    'CANCELLED DUE TO TRANSFER TO ANOTHER ACCOUNT'
]

df['is_fraud'] = df['account_status'].apply(lambda x: 1 if x in fraud_statuses else 0)

In [8]:
from sklearn.preprocessing import LabelEncoder

# List of columns to encode
categorical_cols = ['fraud_type', 'fraud_observation', 'address_reference',
                    'account_status', 'device_code']

# Initialize the encoder
le = LabelEncoder()

# Apply label encoding to each categorical column
for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

# Now your DataFrame has label-encoded values in those columns
print(df.head())

   customer_number  fraud_case_number detection_date  fraud_type  \
0        201995931           496808.0     2020-02-13          19
1        200872755           224397.0     2011-12-15          44
2        200264239           200867.0     2011-04-25          44
3        200062554           389751.0     2016-06-09          24
4        200318029           398508.0     2016-11-23          15

   fraud_observation  address_reference  total_recovered_amount  \
0              10904              12305                112105.0
1              15044              21170                475486.0
2                  0              25000                511261.0
3               4688              22376                641597.0
4               6726              22322               1841235.0

   recovery_number  account_status  device_code  power_capacity_kw  quantity  \
0      435204984.0               9           29              200.0       1.0
1      241419588.0               9          118              100.0       3.0
2      221271745.0               9          104              190.0       1.0
3      332281283.0               8           50              160.0       2.0
4      343215232.0              10           40             1000.0       1.0

   daily_usage_hours  is_fraud
0                8.0         0
1               10.0         0
2               14.0         0
3               14.0         0
4                2.0         1

In [9]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [10]:
scaler = StandardScaler()

# Scale all features except customer number
scaled_features = scaler.fit_transform(df.drop(['customer_number','is_fraud','detection_date'], axis=1))

In [11]:
df['total_power'] = df['device_code'] * df['power_capacity_kw'] * df['quantity']

In [12]:
df.loc[0]

customer_number             201995931
fraud_case_number            496808.0
detection_date             2020-02-13
fraud_type                         19
fraud_observation               10904
address_reference               12305
total_recovered_amount       112105.0
recovery_number           435204984.0
account_status                      9
device_code                        29
power_capacity_kw               200.0
quantity                          1.0
daily_usage_hours                 8.0
is_fraud                            0
total_power                    5800.0
Name: 0, dtype: object

In [13]:
df.drop(['device_code', 'power_capacity_kw', 'quantity'], axis=1, inplace=True)

print(df)

        customer_number  fraud_case_number detection_date  fraud_type  \
0             201995931           496808.0     2020-02-13          19
1             200872755           224397.0     2011-12-15          44
2             200264239           200867.0     2011-04-25          44
3             200062554           389751.0     2016-06-09          24
4             200318029           398508.0     2016-11-23          15
...                 ...                ...            ...         ...
128697        200724854           393395.0     2016-08-03          19
128698        202002652           398533.0     2016-11-24          27
128699        200269398           463135.0     2019-09-19          47
128700        201004711           217446.0     2011-10-10           4
128701        201631766           410580.0     2017-06-17           4

        fraud_observation  address_reference  total_recovered_amount  \
0                   10904              12305                112105.0
1                   15044              21170                475486.0
2                       0              25000                511261.0
3                    4688              22376                641597.0
4                    6726              22322               1841235.0
...                   ...                ...                     ...
128697              12115               8642               1256649.0
128698                  0              13155              13388135.0
128699              13499              22467                300237.0
128700              16252               5488                200458.0
128701               8130               1149                448711.0

        recovery_number  account_status  daily_usage_hours  is_fraud  \
0           435204984.0               9                8.0         0
1           241419588.0               9               10.0         0
2           221271745.0               9               14.0         0
3           332281283.0               8               14.0         0
4           343215232.0              10                2.0         1
...                 ...             ...                ...       ...
128697      336142124.0               9               12.0         0
128698      343262529.0               3               12.0         1
128699      421510728.0               3               10.0         1
128700      239129947.0               9                5.0         0
128701      356458735.0               8                NaN         0

        total_power
0            5800.0
1           35400.0
2           19760.0
3           16000.0
4           40000.0
...             ...
128697          0.0
128698          0.0
128699       6600.0
128700      12000.0
128701          NaN

[128702 rows x 12 columns]

In [14]:
df['totalfraud']=df['fraud_type']+df['fraud_observation']

In [15]:
df.drop(['fraud_type', 'fraud_observation'], axis=1, inplace=True)

print(df)

        customer_number  fraud_case_number detection_date  address_reference  \
0             201995931           496808.0     2020-02-13              12305
1             200872755           224397.0     2011-12-15              21170
2             200264239           200867.0     2011-04-25              25000
3             200062554           389751.0     2016-06-09              22376
4             200318029           398508.0     2016-11-23              22322
...                 ...                ...            ...                ...
128697        200724854           393395.0     2016-08-03               8642
128698        202002652           398533.0     2016-11-24              13155
128699        200269398           463135.0     2019-09-19              22467
128700        201004711           217446.0     2011-10-10               5488
128701        201631766           410580.0     2017-06-17               1149

        total_recovered_amount  recovery_number  account_status  \
0                     112105.0      435204984.0               9
1                     475486.0      241419588.0               9
2                     511261.0      221271745.0               9
3                     641597.0      332281283.0               8
4                    1841235.0      343215232.0              10
...                        ...              ...             ...
128697               1256649.0      336142124.0               9
128698              13388135.0      343262529.0               3
128699                300237.0      421510728.0               3
128700                200458.0      239129947.0               9
128701                448711.0      356458735.0               8

        daily_usage_hours  is_fraud  total_power  totalfraud
0                     8.0         0       5800.0       10923
1                    10.0         0      35400.0       15088
2                    14.0         0      19760.0          44
3                    14.0         0      16000.0        4712
4                     2.0         1      40000.0        6741
...                   ...       ...          ...         ...
128697               12.0         0          0.0       12134
128698               12.0         1          0.0          27
128699               10.0         1       6600.0       13546
128700                5.0         0      12000.0       16256
128701                NaN         0          NaN        8134

[128702 rows x 11 columns]

In [16]:
df.head()

,customer_number,fraud_case_number,detection_date,address_reference,total_recovered_amount,recovery_number,account_status,daily_usage_hours,is_fraud,total_power,totalfraud
0,201995931,496808.0,2020-02-13,12305,112105.0,435204984.0,9,8.0,0,5800.0,10923
1,200872755,224397.0,2011-12-15,21170,475486.0,241419588.0,9,10.0,0,35400.0,15088
2,200264239,200867.0,2011-04-25,25000,511261.0,221271745.0,9,14.0,0,19760.0,44
3,200062554,389751.0,2016-06-09,22376,641597.0,332281283.0,8,14.0,0,16000.0,4712
4,200318029,398508.0,2016-11-23,22322,1841235.0,343215232.0,10,2.0,1,40000.0,6741

In [17]:
df['estimated_daily_energy_consumption'] = df['daily_usage_hours'] * df['total_power']
df.drop(['daily_usage_hours', 'total_power'], axis=1, inplace=True)
print(df.head())

   customer_number  fraud_case_number detection_date  address_reference  \
0        201995931           496808.0     2020-02-13              12305
1        200872755           224397.0     2011-12-15              21170
2        200264239           200867.0     2011-04-25              25000
3        200062554           389751.0     2016-06-09              22376
4        200318029           398508.0     2016-11-23              22322

   total_recovered_amount  recovery_number  account_status  is_fraud  \
0                112105.0      435204984.0               9         0
1                475486.0      241419588.0               9         0
2                511261.0      221271745.0               9         0
3                641597.0      332281283.0               8         0
4               1841235.0      343215232.0              10         1

   totalfraud  estimated_daily_energy_consumption
0       10923                             46400.0
1       15088                            354000.0
2          44                            276640.0
3        4712                            224000.0
4        6741                             80000.0

In [18]:
df.head()

,customer_number,fraud_case_number,detection_date,address_reference,total_recovered_amount,recovery_number,account_status,is_fraud,totalfraud,estimated_daily_energy_consumption
0,201995931,496808.0,2020-02-13,12305,112105.0,435204984.0,9,0,10923,46400.0
1,200872755,224397.0,2011-12-15,21170,475486.0,241419588.0,9,0,15088,354000.0
2,200264239,200867.0,2011-04-25,25000,511261.0,221271745.0,9,0,44,276640.0
3,200062554,389751.0,2016-06-09,22376,641597.0,332281283.0,8,0,4712,224000.0
4,200318029,398508.0,2016-11-23,22322,1841235.0,343215232.0,10,1,6741,80000.0

In [19]:
path1="/content/gdrive/My Drive/ Dataset/validation_data.csv"

In [20]:
df1=pd.read_csv(path1)

In [21]:
df['customer_number'] = df['customer_number'].astype(str).str.replace(r'[^0-9]', '', regex=True)
df['customer_number'] = df['customer_number'].astype('float64').astype('int64')
df3=pd.merge(df,df1,left_on='customer_number', right_on='SERVICE_NBR', how='inner')

In [22]:
df3.loc[0]

customer_number                         200872755
fraud_case_number                        224397.0
detection_date                         2011-12-15
address_reference                           21170
total_recovered_amount                   475486.0
recovery_number                       241419588.0
account_status                                  9
is_fraud                                        0
totalfraud                                  15088
estimated_daily_energy_consumption       354000.0
PHASE                                      230219
TARIFF                                     165194
POWER_SUSCRIBED                         -0.332808
TENSION                                    230514
DIVISION                                    18100
ACTIVITY_CMS                               220294
REGION                                      91875
AGENCY                                       4833
payment_mode                               121960
IsActive                                        1
Tenure_Days                              1.838453
Avg_Consumption                         -0.002804
Max_Consumption                         -0.002566
Total_Payment                           -0.168012
Spike_Count                             -0.718519
Has_inspected                                   1
inspection_count                                1
fraud_found_category                            1
Found_fraud                                     1
SERVICE_NBR                             200872755
Name: 0, dtype: object

In [23]:
import pandas as pd
import numpy as np

# Sample — assuming df is your DataFrame
# Target: 'Found_fraud'

# Convert 'detection_date' to datetime and then to ordinal
df3['detection_date'] = pd.to_datetime(df3['detection_date'], errors='coerce').apply(lambda x: x.toordinal() if pd.notna(x) else -1)

# Convert 'recovery_number' to numeric, coercing errors
df3['recovery_number'] = pd.to_numeric(df3['recovery_number'], errors='coerce')

# Impute NaN values in 'estimated_daily_energy_consumption' with the mean
df3['estimated_daily_energy_consumption'].fillna(df3['estimated_daily_energy_consumption'].mean(), inplace=True)


X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud']

# Convert to numpy
X = X.values
y = y.values

/tmp/ipython-input-1817999942.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['estimated_daily_energy_consumption'].fillna(df3['estimated_daily_energy_consumption'].mean(), inplace=True)

In [24]:
# Reshape (samples, time_steps, features)
X = X.reshape((X.shape[0], X.shape[1], 1))

In [26]:
 from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, precision_recall_curve, auc
from xgboost import XGBClassifier
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# Prepare data
X = df3.drop(columns=['Found_fraud'])
y = df3['Found_fraud'].values

# Impute missing values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

# KMeans clustering (optional — if you feel clustering adds value)
kmeans = KMeans(n_clusters=5, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

# Add cluster labels as feature
X_clustered = np.concatenate([X_scaled, cluster_labels.reshape(-1, 1)], axis=1)

# Stratified CV setup
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# For metrics
all_y_true, all_y_pred, all_y_prob = [], [], []

for fold, (train_idx, val_idx) in enumerate(cv.split(X_clustered, y)):
    print(f"\n▶️ Fold {fold+1}")

    # Split data
    X_train, X_val = X_clustered[train_idx], X_clustered[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    # Autoencoder definition
    input_dim = X_train.shape[1]
    input_layer = Input(shape=(input_dim,))
    encoded = Dense(64, activation='relu')(input_layer)
    encoded = Dense(32, activation='relu')(encoded)
    bottleneck = Dense(16, activation='relu')(encoded)
    decoded = Dense(32, activation='relu')(bottleneck)
    decoded = Dense(64, activation='relu')(decoded)
    output_layer = Dense(input_dim, activation='linear')(decoded)

    autoencoder = Model(inputs=input_layer, outputs=output_layer)
    encoder = Model(inputs=input_layer, outputs=bottleneck)

    autoencoder.compile(optimizer=Adam(learning_rate=0.001), loss='mse')

    # Train autoencoder on training fold only
    autoencoder.fit(X_train, X_train,
                    epochs=50, batch_size=32, shuffle=True,
                    validation_split=0.2, verbose=0)

    # Transform data through bottleneck
    X_train_embedded = encoder.predict(X_train)
    X_val_embedded = encoder.predict(X_val)

    # XGBoost classifier
    xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
    xgb.fit(X_train_embedded, y_train)

    # Predict on validation fold
    y_val_pred = xgb.predict(X_val_embedded)
    y_val_prob = xgb.predict_proba(X_val_embedded)[:, 1]

    # Collect results
    all_y_true.extend(y_val)
    all_y_pred.extend(y_val_pred)
    all_y_prob.extend(y_val_prob)

# Final metrics after CV
cm = confusion_matrix(all_y_true, all_y_pred)
tn, fp, fn, tp = cm.ravel()

print("\nFinal Confusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(all_y_true, all_y_pred, zero_division=0))
print("\nROC AUC Score:", roc_auc_score(all_y_true, all_y_prob))

# Precision-Recall AUC
precision, recall, _ = precision_recall_curve(all_y_true, all_y_prob)
pr_auc = auc(recall, precision)
print("Precision-Recall AUC:", pr_auc)

# Class-wise accuracy
accuracy_class_0 = tn / (tn + fp)
accuracy_class_1 = tp / (tp + fn)
print(f"\nAccuracy for Class 0: {accuracy_class_0:.4f}")
print(f"Accuracy for Class 1: {accuracy_class_1:.4f}")

▶️ Fold 1
287/287 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 2
287/287 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 3
287/287 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

▶️ Fold 4
287/287 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

▶️ Fold 5
287/287 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

Final Confusion Matrix:
 [[   47     1]
 [    1 11426]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        48
           1       1.00      1.00      1.00     11427

    accuracy                           1.00     11475
   macro avg       0.99      0.99      0.99     11475
weighted avg       1.00      1.00      1.00     11475


ROC AUC Score: 0.9999653598203087
Precision-Recall AUC: 0.9999998544251539

Accuracy for Class 0: 0.9792
Accuracy for Class 1: 0.9999